---
- name: RPM key is imported and repo file is created
  block:
    - name: rpm gpg key is installed
      rpm_key:
        state: present
        key: "{{ item.gpgkey }}"
        fingerprint: "{{ item.fingerprint | default(omit) }}"
      when: item.gpgkey is defined

    - name: rpm repo file is created
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description | default(omit) }}"
        baseurl: "{{ item.baseurl }}"
        enabled: "{{ item.enabled | default(1) }}"
        gpgcheck: "{{ item.gpgcheck | default(0) }}"
        gpgkey: "{{ item.gpgkey | default(omit) }}"
  become: true
  when:
    - ansible_distribution == "RedHat"
      or ansible_distribution == "CentOS"
      or ansible_distribution == "Fedora"

- name: DEB key is imported and apt file is create
  block:
    - name: gpg is installed
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - gnupg-agent
          - software-properties-common
        state: present

    - name: apt gpg key is present
      apt_key:
        state: present
        url: "{{ item.gpgkey }}"
        id: "{{ item.id | default(omit) }}"
      when: item.gpgkey is defined

    - name: apt repository file is created
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state | default('present') }}"
        filename: "{{ item.filename | default(omit) }}"
        update_cache: true
  become: true
  when:
    - ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
