---
# Users and groups configuration for ansible-cmdb

- name: defined groups are created
  group:
    name: "{{ item.group }}"
    state: present
  loop: "{{ ansible-cmdb_users }}"
  become: true

- name: users added to secondary groups
  user:
    name: "{{ item.user }}"
    append: true
    groups: "{{ item.group }}"
  become: true
  loop: "{{ ansible-cmdb_users }}"
